In [1]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

In [2]:
data = pd.read_csv("jester-data-1.csv", header = None)
d = data.to_latex()
text_file = open("Data_Output.txt", "w")
text_file.write(d)
text_file.close()

In [3]:
train, validate, test = np.split(data, [int(.8*len(data)), int(.9*len(data))])

In [4]:
del train[0]

In [5]:
n_features = 2

user_ratings = train.values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_features))
latent_item_features = np.random.random((user_ratings.shape[1],n_features))


In [6]:
latent_item_features

array([[ 0.482,  0.357],
       [ 0.636,  0.026],
       [ 0.208,  0.956],
       [ 0.249,  0.483],
       [ 0.026,  0.463],
       [ 0.811,  0.889],
       [ 0.08 ,  0.965],
       [ 0.629,  0.863],
       [ 0.565,  0.9  ],
       [ 0.431,  0.932],
       [ 0.479,  0.35 ],
       [ 0.118,  0.572],
       [ 0.17 ,  0.047],
       [ 0.347,  0.264],
       [ 0.344,  0.981],
       [ 0.207,  0.761],
       [ 0.086,  0.805],
       [ 0.805,  0.111],
       [ 0.105,  0.728],
       [ 0.862,  0.495],
       [ 0.157,  0.715],
       [ 0.756,  0.411],
       [ 0.934,  0.356],
       [ 0.307,  0.965],
       [ 0.003,  0.855],
       [ 0.662,  0.526],
       [ 0.639,  0.1  ],
       [ 0.924,  0.144],
       [ 0.798,  0.195],
       [ 0.523,  0.997],
       [ 0.633,  0.533],
       [ 0.389,  0.605],
       [ 0.186,  0.169],
       [ 0.179,  0.428],
       [ 0.228,  0.848],
       [ 0.27 ,  0.235],
       [ 0.006,  0.14 ],
       [ 0.315,  0.068],
       [ 0.948,  0.52 ],
       [ 0.353,  0.41 ],


In [7]:
latent_user_preferences

array([[ 0.807,  0.248],
       [ 0.207,  0.471],
       [ 0.629,  0.683],
       ..., 
       [ 0.102,  0.652],
       [ 0.195,  0.297],
       [ 0.794,  0.847]])

In [8]:
def predict_rating(user_id,item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)

def train(user_id, item_id, rating,alpha = 0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  ( prediction_rating- rating );
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    


def sgd(iterations = 30):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(0,iterations):
        error = []
        for user_id in range(0,latent_user_preferences.shape[0]):
            for item_id in range(0,latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if(rating != 99):
                    err = train(user_id,item_id,rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if(iteration%1 == 0 ):
            print mse

In [9]:
sgd()

26.0795115458
25.0832717199
24.7512605796
24.5044605914
24.2676227099
24.0292719432
23.7878073492
23.5435983724
23.2973788434
23.0497334498
22.8008312116
22.5502351919
22.2967571422
22.038370346
21.7722215803
21.4948093294
21.2024158734
20.8918747124
20.5616844987
20.2133091496
19.8522459287
19.4882366597
19.1340974342
18.8032165562
18.5065801048
18.250594586
18.0365490964
17.8616121975
17.7205620251
17.6074121046


In [10]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[-3.1  , -4.398, -5.272, ..., -2.295, -4.266, -2.015],
       [ 2.859,  3.4  ,  3.715, ...,  2.687,  3.079,  2.864],
       [ 5.215,  5.261,  5.132, ...,  5.722,  4.39 ,  6.667],
       ..., 
       [ 3.327,  3.214,  3.026, ...,  3.774,  2.616,  4.472],
       [ 1.156,  0.848,  0.582, ...,  1.545,  0.559,  1.966],
       [ 2.119,  2.092,  2.005, ...,  2.364,  1.724,  2.779]])

In [11]:
values = [zip(user_ratings[i], predictions[i]) for i in range(0,predictions.shape[0])]
comparison_data = pd.DataFrame(values)
del data[0]
comparison_data.columns = data.columns
comparison_data.applymap(lambda (x,y): "(%2.3f|%2.3f)"%(x,y))

1                2                3                4    \
0      (-7.820|-3.100)   (8.790|-4.398)  (-9.660|-5.272)  (-8.160|-8.875)   
1        (4.080|2.859)   (-0.290|3.400)    (6.360|3.715)    (4.370|4.657)   
2       (99.000|5.215)   (99.000|5.261)   (99.000|5.132)   (99.000|3.435)   
3       (99.000|1.234)    (8.350|0.835)   (99.000|0.499)  (99.000|-1.388)   
4        (8.500|3.130)    (4.610|2.933)   (-4.170|2.688)   (-5.390|0.854)   
5      (-6.170|-4.868)  (-3.540|-5.637)   (0.440|-6.061)  (-8.500|-7.115)   
6       (99.000|3.213)   (99.000|3.272)   (99.000|3.217)   (99.000|2.285)   
7       (6.840|-2.736)   (3.160|-3.537)   (9.170|-4.050)  (-6.210|-5.979)   
8      (-3.790|-0.674)  (-3.540|-1.353)  (-9.420|-1.840)  (-6.890|-4.063)   
9        (3.010|4.533)    (5.150|4.930)    (5.150|5.084)    (3.010|4.903)   
10      (-2.910|2.253)    (4.080|1.769)   (99.000|1.335)  (99.000|-1.230)   
11       (1.310|0.216)   (1.800|-0.089)   (2.570|-0.324)  (-2.380|-1.508)   
12      (99.000|4.085)   (99.000|4.052)   (99.000|3.899)   (99.000|2.319)   
13       (9.220|4.219)    (9.270|4.428)    (9.220|4.453)    (8.300|3.707)   
14      (8.790|-0.624)  (-5.780|-0.720)   (6.020|-0.773)   (3.690|-0.900)   
15     (-3.500|-0.137)   (1.550|-0.491)   (2.330|-0.752)  (-4.130|-1.988)   
16      (99.000|1.497)   (-9.270|1.391)   (99.000|1.264)   (99.000|0.345)   
17       (3.160|3.650)    (7.620|3.890)    (3.790|3.955)    (8.250|3.521)   
18       (4.220|0.555)    (3.640|0.255)   (99.000|0.014)  (99.000|-1.270)   
19      (99.000|0.601)    (7.620|0.394)   (99.000|0.220)  (99.000|-0.747)   
20      (2.570|-0.087)  (-0.730|-0.235)  (99.000|-0.343)  (99.000|-0.850)   
21       (7.280|0.848)    (5.390|0.621)   (99.000|0.425)  (99.000|-0.701)   
22       (2.720|2.952)    (4.170|2.938)    (6.500|2.836)   (-3.540|1.733)   
23       (2.090|0.566)  (-7.570|-0.036)   (4.170|-0.505)  (-8.400|-2.893)   
24      (-3.930|0.810)   (-1.170|0.405)    (2.280|0.076)  (-0.440|-1.686)   
25      (99.000|3.832)    (5.490|3.963)    (3.450|3.942)   (99.000|3.052)   
26      (99.000|1.692)    (5.830|1.722)   (99.000|1.692)   (99.000|1.198)   
27      (0.490|-2.127)   (0.150|-2.563)   (0.150|-2.823)  (-9.560|-3.645)   
28      (99.000|1.411)   (99.000|1.172)   (99.000|0.949)  (99.000|-0.423)   
29      (99.000|2.492)    (4.080|2.516)   (99.000|2.456)   (99.000|1.652)   
...                ...              ...              ...              ...   
19956    (8.740|0.774)    (7.860|0.605)   (-9.320|0.455)  (-9.510|-0.431)   
19957    (6.410|1.591)    (3.980|1.194)   (99.000|0.847)  (99.000|-1.162)   
19958   (-5.190|0.322)   (-5.920|0.326)    (6.550|0.318)   (-6.840|0.216)   
19959   (99.000|1.845)   (99.000|1.746)   (99.000|1.614)   (99.000|0.594)   
19960   (99.000|0.693)   (99.000|0.404)   (99.000|0.167)  (99.000|-1.129)   
19961   (-1.550|1.736)    (0.530|1.323)    (8.540|0.959)   (1.940|-1.164)   
19962  (-8.010|-3.458)  (-7.720|-3.708)  (-8.880|-3.787)   (8.350|-3.461)   
19963   (9.270|-0.284)  (-6.460|-0.339)   (9.130|-0.372)  (-8.500|-0.470)   
19964   (99.000|4.196)    (6.700|4.102)   (-8.690|3.901)   (99.000|2.061)   
19965  (99.000|-0.854)  (99.000|-1.718)  (99.000|-2.337)  (99.000|-5.167)   
19966   (-1.600|2.145)    (3.540|2.202)   (-1.990|2.178)   (-0.390|1.621)   
19967   (6.360|-3.349)  (-0.340|-4.198)  (-4.170|-4.728)  (-9.560|-6.613)   
19968   (99.000|6.549)    (8.980|6.869)   (99.000|6.904)    (9.130|5.725)   
19969  (-0.440|-0.205)  (-0.290|-0.645)  (-0.440|-0.968)   (2.620|-2.492)   
19970    (0.580|1.895)   (-0.780|1.852)    (0.830|1.761)   (-1.020|0.931)   
19971    (3.690|1.170)    (5.190|1.017)    (4.810|0.866)  (99.000|-0.106)   
19972    (4.220|1.138)    (0.290|0.147)   (4.130|-0.630)  (-9.810|-4.632)   
19973  (-2.140|-0.154)  (-6.410|-0.457)  (-3.830|-0.679)  (-3.930|-1.725)   
19974    (4.270|3.009)    (5.830|2.832)    (5.830|2.605)    (4.270|0.888)   
19975    (4.220|0.347)    (2.820|0.262)    (2.860|0.187)  (-3.790|-0.247)   
19976   (99.000

In [12]:
comparison_data

1                          2    \
0       (-7.82, -3.09999853081)     (8.79, -4.39795826531)   
1         (4.08, 2.85874525184)     (-0.29, 3.39971173462)   
2         (99.0, 5.21509962271)      (99.0, 5.26093287126)   
3         (99.0, 1.23360065635)     (8.35, 0.835297479307)   
4          (8.5, 3.13018552336)      (4.61, 2.93320939471)   
5       (-6.17, -4.86781300801)    (-3.54, -5.63749051326)   
6         (99.0, 3.21274708314)      (99.0, 3.27245681513)   
7        (6.84, -2.73617174945)     (3.16, -3.53684292372)   
8      (-3.79, -0.674192588678)    (-3.54, -1.35307453602)   
9         (3.01, 4.53327869609)      (5.15, 4.92954324877)   
10       (-2.91, 2.25345052802)      (4.08, 1.76857580997)   
11       (1.31, 0.215707177915)    (1.8, -0.0891968285958)   
12        (99.0, 4.08497001344)      (99.0, 4.05173574005)   
13        (9.22, 4.21874296411)      (9.27, 4.42849302944)   
14      (8.79, -0.623997332077)   (-5.78, -0.720401989776)   
15      (-3.5, -0.137241599439)    (1.55, -0.491378307974)   
16        (99.0, 1.49659937684)     (-9.27, 1.39054011853)   
17        (3.16, 3.64995490444)      (7.62, 3.88970615025)   
18       (4.22, 0.554623729784)     (3.64, 0.255456126166)   
19       (99.0, 0.601345540456)     (7.62, 0.394088522242)   
20     (2.57, -0.0869976821132)   (-0.73, -0.235148740338)   
21       (7.28, 0.848243196074)     (5.39, 0.621366036785)   
22        (2.72, 2.95166523338)      (4.17, 2.93839613744)   
23       (2.09, 0.565819531101)  (-7.57, -0.0364408161361)   
24      (-3.93, 0.810244497797)    (-1.17, 0.404639010024)   
25        (99.0, 3.83160085865)      (5.49, 3.96349848984)   
26         (99.0, 1.6916425046)      (5.83, 1.72214997722)   
27       (0.49, -2.12749899541)     (0.15, -2.56337622797)   
28        (99.0, 1.41069439226)      (99.0, 1.17172157338)   
29        (99.0, 2.49160498099)      (4.08, 2.51558384845)   
...                         ...                        ...   
19956    (8.74, 0.773564350638)     (7.86, 0.605414967672)   
19957     (6.41, 1.59098154741)      (3.98, 1.19408376883)   
19958   (-5.19, 0.322072914329)    (-5.92, 0.325631051345)   
19959     (99.0, 1.84505631177)      (99.0, 1.74581509305)   
19960    (99.0, 0.692867782644)     (99.0, 0.404214667562)   
19961    (-1.55, 1.73640124074)      (0.53, 1.32258745809)   
19962   (-8.01, -3.45761841649)    (-7.72, -3.70810877212)   
19963   (9.27, -0.284141372613)   (-6.46, -0.339312819545)   
19964      (99.0, 4.1958484718)       (6.7, 4.10206229517)   
19965   (99.0, -0.854055281559)     (99.0, -1.71774013737)   
19966     (-1.6, 2.14452962045)      (3.54, 2.20211592994)   
19967    (6.36, -3.34895018685)    (-0.34, -4.19790744816)   
19968     (99.0, 6.54890536361)      (8.98, 6.86901200538)   
19969  (-0.44, -0.204644978722)   (-0.29, -0.644841135769)   
19970     (0.58, 1.89451708309)     (-0.78, 1.85222670997)   
19971     (3.69, 1.16980418327)      (5.19, 1.01704179789)   
19972     (4.22, 1.13798954623)     (0.29, 0.147190489138)   
19973  (-2.14, -0.153943774255)   (-6.41, -0.457195016989)   
19974     (4.27, 3.00874900077)      (5.83, 2.83179380126)   
19975    (4.22, 0.347467783046)     (2.82, 0.262000753329)   
19976     (99.0, 2.14820623739)      (99.0, 1.85305845856)   
19977     (9.27, 1.02944728924)    (-4.95, 0.208881326132)   
19978    (4.37, -4.16554588385)    (-7.14, -4.63566360188)   
19979   (-5.63, -2.68916826454)    (-4.95, -2.90456453128)   
19980     (99.0, 2.43535365901)      (99.0, 2.25721502671)   
19981    (1.55, -2.32450151236)    (-3.45, -3.25320071099)   
19982     (99.0, 1.72840103353)      (99.0, 1.61214746317)   
19983    (-0.68, 3.32728279638)     (-4.56, 3.21433848335)   
19984     (99.0, 1.15620528419)     (99.0, 0.848429256335)   
19985     (2.04, 2.11880221944)     (-2.23, 2.09158881341)   

                            3                         4    \
0       (-9.66, -5.27233622531)   (-8.16, -8.87515419376)   
1         (6.36, 3.71511114782)     (4.37, 4.65687072536)   


In [13]:
d = comparison_data.to_latex()
text_file = open("comparison_new.txt", "w")
text_file.write(d)
text_file.close()